name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * * '

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image: ["swift:5.1", "swiftlang/swift:nightly-5.2", "swiftlang/swift:nightly"]
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Release Build
      run: swift build -v -c release
    - name: Debug Build
      run: swift build -v -c debug

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Release Build
      run: swift build -v -c release
    - name: Debug Build
      run: swift build -v -c debug
